apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-app
  template:
    metadata:
      labels:
        app: pdf-app
    spec:
      containers:
      - name: pdf-app-container
        image: public.ecr.aws/u4i0c1o5/pdf_app:latest
        ports:
        - containerPort: 8501
